export const mockClients = [
  {
    id: 1,
    name: "Ana García",
    avatar: "https://i.pravatar.cc/150?img=1",
    paymentDay: 5,
    membershipType: "Flex",
    flexSubcategory: "Basic",
    hoursUsed: 80,
    totalHours: 100,
    copiesUsed: 150,
    totalCopies: 200,
    paymentStatus: "Pagado",
    interiorNumber: "101"
  },
  {
    id: 2,
    name: "Carlos Rodríguez",
    avatar: "https://i.pravatar.cc/150?img=2",
    paymentDay: 15,
    membershipType: "My Office",
    hoursUsed: 45,
    totalHours: 60,
    copiesUsed: 80,
    totalCopies: 100,
    paymentStatus: "Pendiente",
    phoneExtension: "2001"
  },
  {
    id: 3,
    name: "Elena Martínez",
    avatar: "https://i.pravatar.cc/150?img=3",
    paymentDay: 10,
    membershipType: "My Desk",
    hoursUsed: 90,
    totalHours: 100,
    copiesUsed: 180,
    totalCopies: 200,
    paymentStatus: "Pagado",
    interiorNumber: "205"
  },
  {
    id: 4,
    name: "David López",
    avatar: "https://i.pravatar.cc/150?img=4",
    paymentDay: 20,
    membershipType: "Virtual",
    hoursUsed: 25,
    totalHours: 40,
    copiesUsed: 30,
    totalCopies: 50,
    paymentStatus: "Pendiente",
    interiorNumber: "301"
  },
  {
    id: 5,
    name: "Isabel Sánchez",
    avatar: "https://i.pravatar.cc/150?img=5",
    paymentDay: 1,
    membershipType: "Flex",
    flexSubcategory: "Starter",
    hoursUsed: 75,
    totalHours: 100,
    copiesUsed: 120,
    totalCopies: 150,
    paymentStatus: "Pagado",
    interiorNumber: "102"
  },
  // ... (resto de los clientes con datos de copias agregados)
];