export const mockClients = [
  {
    id: 1,
    name: "Ana García",
    avatar: "https://i.pravatar.cc/150?img=1",
    paymentDay:'05',
    membershipType: "Flex",
    flexSubcategory: "Basic",
    hoursUsed: 80,
    totalHours: 100,
    copiesUsed: 150,
    totalCopies: 200,
    paymentStatus: "Pagado",
    interiorNumber: "101"
  },
  {
    id: 2,
    name: "Carlos Rodríguez",
    avatar: "https://i.pravatar.cc/150?img=2",
    paymentDay: '15',
    membershipType: "My Office",
    hoursUsed: 45,
    totalHours: 60,
    copiesUsed: 80,
    totalCopies: 100,
    paymentStatus: "Pendiente",
    phoneExtension: "2001"
  },
  {
    id: 3,
    name: "Elena Martínez",
    avatar: "https://i.pravatar.cc/150?img=3",
    paymentDay: '10',
    membershipType: "My Desk",
    hoursUsed: 90,
    totalHours: 100,
    copiesUsed: 180,
    totalCopies: 200,
    paymentStatus: "Pagado",
    interiorNumber: "205"
  },
  {
    id: 4,
    name: "David López",
    avatar: "https://i.pravatar.cc/150?img=4",
    paymentDay: '20',
    membershipType: "Virtual",
    hoursUsed: 25,
    totalHours: 40,
    copiesUsed: 30,
    totalCopies: 50,
    paymentStatus: "Pendiente",
    interiorNumber: "301"
  },
  {
    id: 5,
    name: "Isabel Sánchez",
    avatar: "https://i.pravatar.cc/150?img=5",
    paymentDay:'01',
    membershipType: "Flex",
    flexSubcategory: "Starter",
    hoursUsed: 75,
    totalHours: 100,
    copiesUsed: 120,
    totalCopies: 150,
    paymentStatus: "Pagado",
    interiorNumber: "102"
  },
  {
    id: 6,
    name: "Fernando Pérez",
    avatar: "https://i.pravatar.cc/150?img=6",
    paymentDay: '25',
    membershipType: "My Office",
    hoursUsed: 30,
    totalHours: 60,
    copiesUsed: 50,
    totalCopies: 100,
    paymentStatus: "Pendiente",
    phoneExtension: "2002"
  },
  {
    id: 7,
    name: "Gloria Gómez",
    avatar: "https://i.pravatar.cc/150?img=7",
    paymentDay: '15',
    membershipType: "My Desk",
    hoursUsed: 80,
    totalHours: 100,
    copiesUsed: 150,
    totalCopies: 200,
    paymentStatus: "Pagado",
    interiorNumber: "206"
  },
  {
    id: 8,
    name: "Hugo Ramírez",
    avatar: "https://i.pravatar.cc/150?img=8",
    paymentDay: '05',
    membershipType: "Virtual",
    hoursUsed: 20,
    totalHours: 40,
    copiesUsed: 30,
    totalCopies: 50,
    paymentStatus: "Pendiente",
    interiorNumber: "302"
  },
  {
    id: 9,
    name: "Julieta Torres",
    avatar: "https://i.pravatar.cc/150?img=9",
    paymentDay: '10',
    membershipType: "Flex",
    flexSubcategory: "Premium",
    hoursUsed: 95,
    totalHours: 100,
    copiesUsed: 190,
    totalCopies: 200,
    paymentStatus: "Pagado",
    interiorNumber: "103"
  },
  {
    id: 10,
    name: "Kevin Vargas",
    avatar: "https://i.pravatar.cc/150?img=10",
    paymentDay: '20',
    membershipType: "My Office",
    hoursUsed: 50,
    totalHours: 60,
    copiesUsed: 90,
    totalCopies: 100,
    paymentStatus: "Pendiente",
    phoneExtension: "2003"
  },
  {
    id: 11,
    name: "Laura Núñez",
    avatar: "https://i.pravatar.cc/150?img=11",
    paymentDay: '15',
    membershipType: "My Desk",
    hoursUsed: 85,
    totalHours: 100,
    copiesUsed: 170,
    totalCopies: 200,
    paymentStatus: "Pagado",
    interiorNumber: "207"
  },
  {
    id: 12,
    name: "Miguel Ortega",
    avatar: "https://i.pravatar.cc/150?img=12",
    paymentDay:'05',
    membershipType: "Virtual",
    hoursUsed: 35,
    totalHours: 40,
    copiesUsed: 40,
    totalCopies: 50,
    paymentStatus: "Pendiente",
    interiorNumber: "303"
  },
  {
    id: 13,
    name: "Natalia Jiménez",
    avatar: "https://i.pravatar.cc/150?img=13",
    paymentDay: '10',
    membershipType: "Flex",
    flexSubcategory: "Business",
    hoursUsed: 80,
    totalHours: 100,
    copiesUsed: 150,
    totalCopies: 200,
    paymentStatus: "Pagado",
    interiorNumber: "104"
  }
  // ... (resto de los clientes con datos de copias agregados)
];